title: survey2gis docs
description: 
theme: just-the-docs
heading_anchors: true
url: https://s2g-docs.survey-tools.org/

aux_links:
  Template Repository: https://github.com/survey2gis/survey2gis-docs
