title: survey2gis docs
description: 
theme: just-the-docs
nav_enabled: true
heading_anchors: true
url: https://survey2gis.github.io/survey2gis-docs/

aux_links:
  Template Repository: https://github.com/survey2gis/survey2gis-docs
