title: survey2gis docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://survey2gis.github.io/survey2gis-docs/

aux_links:
  Template Repository: https://survey2gis.github.io/survey2gis-docs/
